-- Clear all existing real-time products
DELETE FROM real_time_products;

-- Ensure text post columns exist
ALTER TABLE real_time_products ADD COLUMN IF NOT EXISTS text_color text;
ALTER TABLE real_time_products ADD COLUMN IF NOT EXISTS is_text_post boolean DEFAULT false;

-- Insert 15 realistic products with only titles filled (no description, no price)
INSERT INTO real_time_products (
  merchant_id,
  title,
  description,
  price,
  location,
  contact_phone,
  category,
  media_url,
  media_type,
  duration,
  views_count,
  contact_clicks,
  is_featured,
  expires_at,
  created_at,
  updated_at,
  text_color,
  is_text_post
) VALUES
-- TEXT POSTS (5 products)
(
  (SELECT id FROM merchants LIMIT 1),
  'Need a study partner for Computer Science finals! Anyone available?',
  NULL,
  NULL,
  'Bingham University',
  '+2349060859789',
  'Study Group',
  'https://via.placeholder.com/400x400/FF6B35/FFFFFF?text=Study+Partner',
  'image',
  NULL,
  12,
  3,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '2 hours',
  NOW() - INTERVAL '2 hours',
  '#4ECDC4',
  true
),
(
  (SELECT id FROM merchants LIMIT 1),
  'Lost my phone in the library! Please help me find it 😢',
  NULL,
  NULL,
  'University of Lagos',
  '+2349060859789',
  'Lost & Found',
  'https://via.placeholder.com/400x400/45B7D1/FFFFFF?text=Lost+Phone',
  'image',
  NULL,
  8,
  1,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '4 hours',
  NOW() - INTERVAL '4 hours',
  '#FF6B35',
  true
),
(
  (SELECT id FROM merchants LIMIT 1),
  'Looking for roommates for off-campus housing near campus',
  NULL,
  NULL,
  'Covenant University',
  '+2349060859789',
  'Housing',
  'https://via.placeholder.com/400x400/96CEB4/FFFFFF?text=Roommates',
  'image',
  NULL,
  15,
  5,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '6 hours',
  NOW() - INTERVAL '6 hours',
  '#DDA0DD',
  true
),
(
  (SELECT id FROM merchants LIMIT 1),
  'Free coding workshop this weekend! Learn Python basics',
  NULL,
  NULL,
  'Obafemi Awolowo University',
  '+2349060859789',
  'Workshop',
  'https://via.placeholder.com/400x400/FFEAA7/FFFFFF?text=Coding+Workshop',
  'image',
  NULL,
  22,
  8,
  true,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '8 hours',
  NOW() - INTERVAL '8 hours',
  '#98D8C8',
  true
),
(
  (SELECT id FROM merchants LIMIT 1),
  'Selling my old textbooks - Engineering and Science subjects',
  NULL,
  NULL,
  'University of Ibadan',
  '+2349060859789',
  'Books',
  'https://via.placeholder.com/400x400/F7DC6F/FFFFFF?text=Textbooks',
  'image',
  NULL,
  18,
  4,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '10 hours',
  NOW() - INTERVAL '10 hours',
  '#85C1E9',
  true
),

-- IMAGE POSTS (5 products) - Only titles filled
(
  (SELECT id FROM merchants LIMIT 1),
  'Gaming laptop for sale - RTX 3060, 16GB RAM, barely used, perfect for students',
  NULL,
  NULL,
  'Bingham University',
  '+2349060859789',
  'Electronics',
  'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&h=600&fit=crop',
  'image',
  NULL,
  25,
  6,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '1 hour',
  NOW() - INTERVAL '1 hour',
  NULL,
  false
),
(
  (SELECT id FROM merchants LIMIT 1),
  'Study desk and chair set - wooden, perfect for dorm room, easy to assemble',
  NULL,
  NULL,
  'University of Lagos',
  '+2349060859789',
  'Furniture',
  'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop',
  'image',
  NULL,
  19,
  4,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '3 hours',
  NOW() - INTERVAL '3 hours',
  NULL,
  false
),
(
  (SELECT id FROM merchants LIMIT 1),
  'iPhone 13 Pro for sale - Sierra Blue, no scratches, perfect condition, comes with charger',
  NULL,
  NULL,
  'Covenant University',
  '+2349060859789',
  'Electronics',
  'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&h=600&fit=crop',
  'image',
  NULL,
  31,
  9,
  true,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '5 hours',
  NOW() - INTERVAL '5 hours',
  NULL,
  false
),
(
  (SELECT id FROM merchants LIMIT 1),
  'Mountain bike for sale - great condition, perfect for campus, includes lock and helmet',
  NULL,
  NULL,
  'Obafemi Awolowo University',
  '+2349060859789',
  'Transportation',
  'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&h=600&fit=crop',
  'image',
  NULL,
  14,
  3,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '7 hours',
  NOW() - INTERVAL '7 hours',
  NULL,
  false
),
(
  (SELECT id FROM merchants LIMIT 1),
  'Mini fridge for dorm room - keeps drinks cold, energy efficient, selling because I moved out',
  NULL,
  NULL,
  'University of Ibadan',
  '+2349060859789',
  'Appliances',
  'https://images.unsplash.com/photo-1571172964276-91faaa704e1f?w=800&h=600&fit=crop',
  'image',
  NULL,
  12,
  2,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '9 hours',
  NOW() - INTERVAL '9 hours',
  NULL,
  false
),

-- VIDEO POSTS (5 products) - Only titles filled
(
  (SELECT id FROM merchants LIMIT 1),
  'DJ equipment set - professional quality, used for campus events, includes mixer and speakers',
  NULL,
  NULL,
  'Bingham University',
  '+2349060859789',
  'Electronics',
  'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4',
  'video',
  30,
  28,
  7,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '2 hours',
  NOW() - INTERVAL '2 hours',
  NULL,
  false
),
(
  (SELECT id FROM merchants LIMIT 1),
  'Home gym setup - bench, weights, resistance bands, perfect for staying fit at home',
  NULL,
  NULL,
  'University of Lagos',
  '+2349060859789',
  'Sports',
  'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_2mb.mp4',
  'video',
  45,
  16,
  4,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '4 hours',
  NOW() - INTERVAL '4 hours',
  NULL,
  false
),
(
  (SELECT id FROM merchants LIMIT 1),
  'PS5 with 5 games - barely used, perfect condition, comes with extra controller',
  NULL,
  NULL,
  'Covenant University',
  '+2349060859789',
  'Electronics',
  'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_5mb.mp4',
  'video',
  60,
  35,
  12,
  true,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '6 hours',
  NOW() - INTERVAL '6 hours',
  NULL,
  false
),
(
  (SELECT id FROM merchants LIMIT 1),
  'Guitar and keyboard for sale - both in excellent condition, perfect for music students',
  NULL,
  NULL,
  'Obafemi Awolowo University',
  '+2349060859789',
  'Musical Instruments',
  'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4',
  'video',
  25,
  11,
  3,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '8 hours',
  NOW() - INTERVAL '8 hours',
  NULL,
  false
),
(
  (SELECT id FROM merchants LIMIT 1),
  'Professional camera with lenses - great for photography students, all equipment well-maintained',
  NULL,
  NULL,
  'University of Ibadan',
  '+2349060859789',
  'Electronics',
  'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_2mb.mp4',
  'video',
  40,
  19,
  6,
  false,
  NOW() + INTERVAL '24 hours',
  NOW() - INTERVAL '10 hours',
  NOW() - INTERVAL '10 hours',
  NULL,
  false
);

-- Update view counts and contact clicks for realism
UPDATE real_time_products SET 
  views_count = FLOOR(RANDOM() * 50) + 5,
  contact_clicks = FLOOR(RANDOM() * 15) + 1
WHERE id IN (SELECT id FROM real_time_products);

-- Set some products as featured
UPDATE real_time_products SET is_featured = true 
WHERE id IN (
  SELECT id FROM real_time_products 
  ORDER BY RANDOM() 
  LIMIT 3
); 